### ISSUE TITLE
Поправить дизайн 

### ISSUE THREAD

**Issue by CyberBirdie** [diekuche/gutenberg#107]
@Xyzjesus @scsi9 
Комментарии по дизайну на текущий момент собраны в пдф тут [https://drive.google.com/drive/folders/1-SrDvAdWhRYBdbOjJlPuGXjX7UFaob7u?usp=share_link](url) + там видо с прототипа фигмы для окошка ассета

**Comment by CyberBirdie** [comment]
Еще содержимое окошка Assets — идет поверх хэдера 
<img width="427" alt="Screenshot 2023-03-26 at 12 16 17" src="https://user-images.githubusercontent.com/112537530/227755038-5a424d35-b0ab-4bfe-a277-4badfa2af82c.png">

**Comment by schnellreich** [comment]
декомпозировали задачи в новые микро-ишью, этот закрываем
