### ISSUE TITLE
Форма создания токена

### ISSUE THREAD

**Issue by Spaider15** [diekuche/gutenberg#12]
Когда будет готова верстка: https://github.com/diekuche/gutenberg/issues/11
Нужно будет всем инпутам добавить обработчики, все данные сохранять, так же нужно будет добавить валидацию для полей, какие обязательны, и какие к ним требования по мин длине и т.д 
Обработчик по сабмиту пусть пока просто все данные выводит в консоль
@schnellreich Добавь плиз требования по валидации к задаче

**Comment by schnellreich** [comment]
По полям:
**Token Name** — обязательное поле. Количество символов 3—50.
**Symbol** — обязательное поле. 2—5 знаков, допустимы буквы и цифры
**Quantity** — обязательное поле, любое целое число
**Decimals** — необязательное поле, дефолтное значение 0, максимальное значение 10
**Logo URL** — необязательное поле, количество символов 3—99

**+ Initial Balance**
**Wallet Address** — необязательное поле, 45 символов, значение начинается с bostrom
**Balance** — необязательное поле, значение ≤ Quantity
! Если указано несколько адресов, сумма значений должна быть ≤ Quantity

**+Token Details** — необязательное поле, количество символов 3—160
