### ISSUE TITLE
Компонент collapse

### ISSUE THREAD

**Issue by Spaider15** [diekuche/gutenberg#4]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/12617760/189061483-b65fdbbf-7b8c-49ea-81da-a6626d8c654d.png">

Нужно создать компонент collapse, пока что сделаем без либ
Например пусть он принимает в пропсах title и children, title это будет текст кнопки, а children скрываться/показываться по клику, состоянием управляй через useState

**Comment by Xyzjesus** [comment]
@Spaider15 правильно понял что без либ сторонних?) то есть на внутренних(react)?
