### ISSUE TITLE
Logic bugs and improvements

### ISSUE THREAD

**Issue by schnellreich** [diekuche/gutenberg#61]
# 1. Mint

### 1.1. If Decimals not specified
Default = 0. 
It is NULL now

### 1.2. If initial Balances not specified
Default = Quantity
It is ERROR now

### 1.3. Return pop-up with status message
Success/Error
It is always success now, if we get the answer from blockchain

use a simple popup design with black text on a white background

### 1.4. Add Minted Token to the Manage Tokens block
If mint status is success and token was created — add token to the list of user's assets

There is no way to find out the address of the token to add it

# 2. Wallet Button

### 2.1. Disconnect wallet
If wallet is connected, then the Wallet button:
on hover — display the text "Disconnect"
on click — disconnect wallet

# 3. Manage Tokens

### 3.1. Update balances after changing wallets
if you change the wallet, the balances of the previous wallet are displayed now

### 3.2. Update balances every 30 sec
For all tokens in the Manage Tokens list

### 3.3. Hide Send and Add Token fields
Send and add token fields should appear after the first click on send and add token buttons

### 3.4. Rename Default Token to BOOT
StBoot is a side project :-)

### 3.5. Delete Token from list Button 
Design is up to you :-)

**Comment by Spaider15** [comment]
After submit token form in success case clear form inputs
