### ISSUE TITLE
Design bugs and improvements

### ISSUE THREAD

**Issue by schnellreich** [diekuche/gutenberg#62]
# Header 

put . after instruction</a>
delete help link
div Header_wallet > delete magrin-left

# Mint
### Styles:
- div Tabs_tabLabel > font-size: 16px
- div MainPage > padding-top: 50px
- div Input_subtitle > font-size: 12px; padding-left: 9px; padding-top: 2px
- div Form_article > padding-left: 5px;
- div Form_dot > height: 43px; min-width: 43px; margin-top: 25px;

### Text:
mark requered fields with red asterisk: name ⃰ , symbol ⃰ , quantity ⃰ 

add requests to fields (to subtitles):
- Token's name (min 3, max 50 symbols)
- Symbol (min 3, max 5 symbols)
- Decimals (max 10 symbols)
- Token details (max 160 symbols) 

rename button "mint!" to “create!”

# Manage Tokens
ManageTok_info > font-size: 12px; padding 1px 10px 5px;

# Footer
before "About" add github icon height: 20px; and link to repo https://github.com/diekuche/gutenberg

**Comment by Xyzjesus** [comment]
![Image](https://user-images.githubusercontent.com/62913761/203403944-301699f7-0b93-4302-b080-47d77f69dd2f.png)

when collapsed, there's no bg after footer
